# Generated by Django 5.1.7 on 2025-04-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_chatroom_remove_message_username_message_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('group', 'Group')], max_length=100),
        ),
    ]
